<?php

namespace rabint\components\grid;

use yii\grid\DataColumn;

class FileColumn extends DataColumn
{

    public $format = 'raw';
    public $ext = null;
    public $size = [50, 50];
    public $enableSorting = false;
    public $filter = false;

    public function init()
    {
//        $this->filterOptions = ['style' => 'max-width:'.$this->size[0].'px;'];
        $this->filterOptions = array_merge(['style' => 'max-width:'.$this->size[0].'px;'], $this->filterOptions);

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getDataCellValue($model, $key, $index)
    {

        $this->filterOptions = ['style' => 'max-width:'.$this->size[0].'px;'];
        $value = parent::getDataCellValue($model, $key, $index);
        if ($this->format == "raw") {
            return \rabint\helpers\html::virtualAttachmentTag($value,$this->ext, [], $this->size);
        }
        return $this->value;
    }

}
