<?php return [
    "AD" => [
        "iso" => "AD",
        "name" => "Andorra",
        "name_fa" => "آندورا"
    ],
    "AE" => ["iso" => "AE", "name" => "United Arab Emirates", "name_fa" => "امارات متحده عربی"],
    "AF" => ["iso" => "AF", "name" => "Afghanistan", "name_fa" => "افغانستان"],
    "AG" => ["iso" => "AG", "name" => "Antigua and Barbuda", "name_fa" => "آنتیگوا و باربودا"],
    "AI" => ["iso" => "AI", "name" => "Anguilla", "name_fa" => "آنگویلا"],
    "AL" => ["iso" => "AL", "name" => "Albania", "name_fa" => "آلبانی"],
    "AM" => ["iso" => "AM", "name" => "Armenia", "name_fa" => "ارمنستان"],
    "AO" => ["iso" => "AO", "name" => "Angola", "name_fa" => "آنگولا"],
    "AQ" => ["iso" => "AQ", "name" => "Antarctica", "name_fa" => "جنوبگان"],
    "AR" => ["iso" => "AR", "name" => "Argentina", "name_fa" => "آرژانتین"],
    "AS" => ["iso" => "AS", "name" => "American Samoa", "name_fa" => "ساموآی آمریکا"],
    "AT" => ["iso" => "AT", "name" => "Austria", "name_fa" => "اتریش"],
    "AU" => ["iso" => "AU", "name" => "Australia", "name_fa" => "استرالیا"],
    "AW" => ["iso" => "AW", "name" => "Aruba", "name_fa" => "آروبا"],
    "AX" => ["iso" => "AX", "name" => "Åland Islands", "name_fa" => "جزایر الند"],
    "AZ" => ["iso" => "AZ", "name" => "Azerbaijan", "name_fa" => "جمهوری آذربایجان"],
    "BA" => ["iso" => "BA", "name" => "Bosnia and Herzegovina", "name_fa" => "بوسنی و هرزگوین"],
    "BB" => ["iso" => "BB", "name" => "Barbados", "name_fa" => "باربادوس"],
    "BD" => ["iso" => "BD", "name" => "Bangladesh", "name_fa" => "بنگلادش"],
    "BE" => ["iso" => "BE", "name" => "Belgium", "name_fa" => "بلژیک"],
    "BF" => ["iso" => "BF", "name" => "Burkina Faso", "name_fa" => "بورکینافاسو"],
    "BG" => ["iso" => "BG", "name" => "Bulgaria", "name_fa" => "بلغارستان"],
    "BH" => ["iso" => "BH", "name" => "Bahrain", "name_fa" => "بحرین"],
    "BI" => ["iso" => "BI", "name" => "Burundi", "name_fa" => "بوروندی"],
    "BJ" => ["iso" => "BJ", "name" => "Benin", "name_fa" => "بنین"],
    "BL" => ["iso" => "BL", "name" => "Saint Barthélemy", "name_fa" => "سنت بارثلمی"],
    "BM" => ["iso" => "BM", "name" => "Bermuda", "name_fa" => "برمودا"],
    "BN" => ["iso" => "BN", "name" => "Brunei Darussalam", "name_fa" => "برونئی"],
    "BO" => ["iso" => "BO", "name" => "Bolivia (Plurinational State of)", "name_fa" => "بولیوی"],
    "BQ" => ["iso" => "BQ", "name" => "Bonaire, Sint Eustatius and Saba", "name_fa" => "جزایر کارائیب هلند"],
    "BR" => ["iso" => "BR", "name" => "Brazil", "name_fa" => "برزیل"],
    "BS" => ["iso" => "BS", "name" => "Bahamas", "name_fa" => "باهاما"],
    "BT" => ["iso" => "BT", "name" => "Bhutan", "name_fa" => "پادشاهی بوتان"],
    "BV" => ["iso" => "BV", "name" => "Bouvet Island", "name_fa" => "جزیره بووه"],
    "BW" => ["iso" => "BW", "name" => "Botswana", "name_fa" => "بوتسوانا"],
    "BY" => ["iso" => "BY", "name" => "Belarus", "name_fa" => "بلاروس"],
    "BZ" => ["iso" => "BZ", "name" => "Belize", "name_fa" => "بلیز"],
    "CA" => ["iso" => "CA", "name" => "Canada", "name_fa" => "کانادا"],
    "CC" => ["iso" => "CC", "name" => "Cocos (Keeling) Islands", "name_fa" => "جزایر کوکوس"],
    "CD" => ["iso" => "CD", "name" => "Congo, Democratic Republic of the", "name_fa" => "جمهوری دموکراتیک کنگو"],
    "CF" => ["iso" => "CF", "name" => "Central African Republic", "name_fa" => "جمهوری آفریقای مرکزی"],
    "CG" => ["iso" => "CG", "name" => "Congo", "name_fa" => "جمهوری کنگو"],
    "CH" => ["iso" => "CH", "name" => "Switzerland", "name_fa" => "سوئیس"],
    "CI" => ["iso" => "CI", "name" => "Côte d'Ivoire", "name_fa" => "ساحل عاج"],
    "CK" => ["iso" => "CK", "name" => "Cook Islands", "name_fa" => "جزایر کوک"],
    "CL" => ["iso" => "CL", "name" => "Chile", "name_fa" => "شیلی"],
    "CM" => ["iso" => "CM", "name" => "Cameroon", "name_fa" => "کامرون"],
    "CN" => ["iso" => "CN", "name" => "China", "name_fa" => "جمهوری خلق چین"],
    "CO" => ["iso" => "CO", "name" => "Colombia", "name_fa" => "کلمبیا"],
    "CR" => ["iso" => "CR", "name" => "Costa Rica", "name_fa" => "کاستاریکا"],
    "CU" => ["iso" => "CU", "name" => "Cuba", "name_fa" => "کوبا"],
    "CV" => ["iso" => "CV", "name" => "Cabo Verde", "name_fa" => "کیپ ورد"],
    "CW" => ["iso" => "CW", "name" => "Curaçao", "name_fa" => "کوراسائو"],
    "CX" => ["iso" => "CX", "name" => "Christmas Island", "name_fa" => "جزیره کریسمس"],
    "CY" => ["iso" => "CY", "name" => "Cyprus", "name_fa" => "قبرس"],
    "CZ" => ["iso" => "CZ", "name" => "Czechia", "name_fa" => "جمهوری چک"],
    "DE" => ["iso" => "DE", "name" => "Germany", "name_fa" => "آلمان"],
    "DJ" => ["iso" => "DJ", "name" => "Djibouti", "name_fa" => "جیبوتی"],
    "DK" => ["iso" => "DK", "name" => "Denmark", "name_fa" => "دانمارک"],
    "DM" => ["iso" => "DM", "name" => "Dominica", "name_fa" => "دومینیکا"],
    "DO" => ["iso" => "DO", "name" => "Dominican Republic", "name_fa" => "جمهوری دومینیکن"],
    "DZ" => ["iso" => "DZ", "name" => "Algeria", "name_fa" => "الجزایر"],
    "EC" => ["iso" => "EC", "name" => "Ecuador", "name_fa" => "اکوادور"],
    "EE" => ["iso" => "EE", "name" => "Estonia", "name_fa" => "استونی"],
    "EG" => ["iso" => "EG", "name" => "Egypt", "name_fa" => "مصر"],
    "EH" => ["iso" => "EH", "name" => "Western Sahara", "name_fa" => "صحرای غربی"],
    "ER" => ["iso" => "ER", "name" => "Eritrea", "name_fa" => "اریتره"],
    "ES" => ["iso" => "ES", "name" => "Spain", "name_fa" => "اسپانیا"],
    "ET" => ["iso" => "ET", "name" => "Ethiopia", "name_fa" => "اتیوپی"],
    "FI" => ["iso" => "FI", "name" => "Finland", "name_fa" => "فنلاند"],
    "FJ" => ["iso" => "FJ", "name" => "Fiji", "name_fa" => "فیجی"],
    "FK" => ["iso" => "FK", "name" => "Falkland Islands (Malvinas)", "name_fa" => "جزایر فالکلند"],
    "FM" => ["iso" => "FM", "name" => "Micronesia (Federated States of)", "name_fa" => "ایالات فدرال میکرونزی"],
    "FO" => ["iso" => "FO", "name" => "Faroe Islands", "name_fa" => "جزایر فارو"],
    "FR" => ["iso" => "FR", "name" => "France", "name_fa" => "فرانسه"],
    "GA" => ["iso" => "GA", "name" => "Gabon", "name_fa" => "گابن"],
    "GB" => ["iso" => "GB", "name" => "United Kingdom of Great Britain and Northern Ireland", "name_fa" => "بریتانیا"],
    "GD" => ["iso" => "GD", "name" => "Grenada", "name_fa" => "گرنادا"],
    "GE" => ["iso" => "GE", "name" => "Georgia", "name_fa" => "گرجستان"],
    "GF" => ["iso" => "GF", "name" => "French Guiana", "name_fa" => "گویان فرانسه"],
    "GG" => ["iso" => "GG", "name" => "Guernsey", "name_fa" => "گرنزی"],
    "GH" => ["iso" => "GH", "name" => "Ghana", "name_fa" => "غنا"],
    "GI" => ["iso" => "GI", "name" => "Gibraltar", "name_fa" => "جبل طارق"],
    "GL" => ["iso" => "GL", "name" => "Greenland", "name_fa" => "گرینلند"],
    "GM" => ["iso" => "GM", "name" => "Gambia", "name_fa" => "گامبیا"],
    "GN" => ["iso" => "GN", "name" => "Guinea", "name_fa" => "گینه"],
    "GP" => ["iso" => "GP", "name" => "Guadeloupe", "name_fa" => "جزیره گوادلوپ"],
    "GQ" => ["iso" => "GQ", "name" => "Equatorial Guinea", "name_fa" => "گینه استوایی"],
    "GR" => ["iso" => "GR", "name" => "Greece", "name_fa" => "یونان"],
    "GS" => [
        "iso" => "GS",
        "name" => "South Georgia and the South Sandwich Islands",
        "name_fa" => "جزایر جورجیای جنوبی و ساندویچ جنوبی"
    ],
    "GT" => ["iso" => "GT", "name" => "Guatemala", "name_fa" => "گواتمالا"],
    "GU" => ["iso" => "GU", "name" => "Guam", "name_fa" => "گوآم"],
    "GW" => ["iso" => "GW", "name" => "Guinea-Bissau", "name_fa" => "گینه بیسائو"],
    "GY" => ["iso" => "GY", "name" => "Guyana", "name_fa" => "گویان"],
    "HK" => ["iso" => "HK", "name" => "Hong Kong", "name_fa" => "هنگ کنگ"],
    "HM" => ["iso" => "HM", "name" => "Heard Island and McDonald Islands", "name_fa" => "جزیره هرد و جزایر مک‌دونالد"],
    "HN" => ["iso" => "HN", "name" => "Honduras", "name_fa" => "هندوراس"],
    "HR" => ["iso" => "HR", "name" => "Croatia", "name_fa" => "کرواسی"],
    "HT" => ["iso" => "HT", "name" => "Haiti", "name_fa" => "هائیتی"],
    "HU" => ["iso" => "HU", "name" => "Hungary", "name_fa" => "مجارستان"],
    "ID" => ["iso" => "ID", "name" => "Indonesia", "name_fa" => "اندونزی"],
    "IE" => ["iso" => "IE", "name" => "Ireland", "name_fa" => "ایرلند"],
    "IL" => ["iso" => "IL", "name" => "Israel", "name_fa" => "اسرائیل"],
    "IM" => ["iso" => "IM", "name" => "Isle of Man", "name_fa" => "جزیره من"],
    "IN" => ["iso" => "IN", "name" => "India", "name_fa" => "هند"],
    "IO" => ["iso" => "IO", "name" => "British Indian Ocean Territory", "name_fa" => "قلمرو بریتانیا در اقیانوس هند"],
    "IQ" => ["iso" => "IQ", "name" => "Iraq", "name_fa" => "عراق"],
    "IR" => ["iso" => "IR", "name" => "Iran (Islamic Republic of)", "name_fa" => "ایران"],
    "IS" => ["iso" => "IS", "name" => "Iceland", "name_fa" => "ایسلند"],
    "IT" => ["iso" => "IT", "name" => "Italy", "name_fa" => "ایتالیا"],
    "JE" => ["iso" => "JE", "name" => "Jersey", "name_fa" => "جرزی"],
    "JM" => ["iso" => "JM", "name" => "Jamaica", "name_fa" => "جامائیکا"],
    "JO" => ["iso" => "JO", "name" => "Jordan", "name_fa" => "اردن"],
    "JP" => ["iso" => "JP", "name" => "Japan", "name_fa" => "ژاپن"],
    "KE" => ["iso" => "KE", "name" => "Kenya", "name_fa" => "کنیا"],
    "KG" => ["iso" => "KG", "name" => "Kyrgyzstan", "name_fa" => "قرقیزستان"],
    "KH" => ["iso" => "KH", "name" => "Cambodia", "name_fa" => "کامبوج"],
    "KI" => ["iso" => "KI", "name" => "Kiribati", "name_fa" => "کیریباتی"],
    "KM" => ["iso" => "KM", "name" => "Comoros", "name_fa" => "مجمع‌الجزایر قمر"],
    "KN" => ["iso" => "KN", "name" => "Saint Kitts and Nevis", "name_fa" => "سنت کیتس و نویس"],
    "KP" => ["iso" => "KP", "name" => "Korea (Democratic People's Republic of)", "name_fa" => "کره شمالی"],
    "KR" => ["iso" => "KR", "name" => "Korea, Republic of", "name_fa" => "کره جنوبی"],
    "KW" => ["iso" => "KW", "name" => "Kuwait", "name_fa" => "کویت"],
    "KY" => ["iso" => "KY", "name" => "Cayman Islands", "name_fa" => "جزایر کیمن"],
    "KZ" => ["iso" => "KZ", "name" => "Kazakhstan", "name_fa" => "قزاقستان"],
    "LA" => ["iso" => "LA", "name" => "Lao People's Democratic Republic", "name_fa" => "لائوس"],
    "LB" => ["iso" => "LB", "name" => "Lebanon", "name_fa" => "لبنان"],
    "LC" => ["iso" => "LC", "name" => "Saint Lucia", "name_fa" => "سنت لوسیا"],
    "LI" => ["iso" => "LI", "name" => "Liechtenstein", "name_fa" => "لیختن‌اشتاین"],
    "LK" => ["iso" => "LK", "name" => "Sri Lanka", "name_fa" => "سری‌لانکا"],
    "LR" => ["iso" => "LR", "name" => "Liberia", "name_fa" => "لیبریا"],
    "LS" => ["iso" => "LS", "name" => "Lesotho", "name_fa" => "لسوتو"],
    "LT" => ["iso" => "LT", "name" => "Lithuania", "name_fa" => "لیتوانی"],
    "LU" => ["iso" => "LU", "name" => "Luxembourg", "name_fa" => "لوکزامبورگ"],
    "LV" => ["iso" => "LV", "name" => "Latvia", "name_fa" => "لتونی"],
    "LY" => ["iso" => "LY", "name" => "Libya", "name_fa" => "لیبی"],
    "MA" => ["iso" => "MA", "name" => "Morocco", "name_fa" => "مراکش"],
    "MC" => ["iso" => "MC", "name" => "Monaco", "name_fa" => "موناکو"],
    "MD" => ["iso" => "MD", "name" => "Moldova,  Republic of", "name_fa" => "مولداوی"],
    "ME" => ["iso" => "ME", "name" => "Montenegro", "name_fa" => "مونته‌نگرو"],
    "MF" => ["iso" => "MF", "name" => "Saint Martin (French part)", "name_fa" => "سنت مارتین فرانسه"],
    "MG" => ["iso" => "MG", "name" => "Madagascar", "name_fa" => "ماداگاسکار"],
    "MH" => ["iso" => "MH", "name" => "Marshall Islands", "name_fa" => "جزایر مارشال"],
    "MK" => ["iso" => "MK", "name" => "Macedonia,  the former Yugoslav Republic of", "name_fa" => "جمهوری مقدونیه"],
    "ML" => ["iso" => "ML", "name" => "Mali", "name_fa" => "مالی"],
    "MM" => ["iso" => "MM", "name" => "Myanmar", "name_fa" => "میانمار"],
    "MN" => ["iso" => "MN", "name" => "Mongolia", "name_fa" => "مغولستان"],
    "MO" => ["iso" => "MO", "name" => "Macao", "name_fa" => "ماکائو"],
    "MP" => ["iso" => "MP", "name" => "Northern Mariana Islands", "name_fa" => "جزایر ماریانای شمالی"],
    "MQ" => ["iso" => "MQ", "name" => "Martinique", "name_fa" => "مارتینیک"],
    "MR" => ["iso" => "MR", "name" => "Mauritania", "name_fa" => "موریتانی"],
    "MS" => ["iso" => "MS", "name" => "Montserrat", "name_fa" => "مونتسرات"],
    "MT" => ["iso" => "MT", "name" => "Malta", "name_fa" => "مالت"],
    "MU" => ["iso" => "MU", "name" => "Mauritius", "name_fa" => "موریس"],
    "MV" => ["iso" => "MV", "name" => "Maldives", "name_fa" => "مالدیو"],
    "MW" => ["iso" => "MW", "name" => "Malawi", "name_fa" => "مالاوی"],
    "MX" => ["iso" => "MX", "name" => "Mexico", "name_fa" => "مکزیک"],
    "MY" => ["iso" => "MY", "name" => "Malaysia", "name_fa" => "مالزی"],
    "MZ" => ["iso" => "MZ", "name" => "Mozambique", "name_fa" => "موزامبیک"],
    "NA" => ["iso" => "NA", "name" => "Namibia", "name_fa" => "نامیبیا"],
    "NC" => ["iso" => "NC", "name" => "New Caledonia", "name_fa" => "کالدونیای جدید"],
    "NE" => ["iso" => "NE", "name" => "Niger", "name_fa" => "نیجر"],
    "NF" => ["iso" => "NF", "name" => "Norfolk Island", "name_fa" => "جزیره نورفک"],
    "NG" => ["iso" => "NG", "name" => "Nigeria", "name_fa" => "نیجریه"],
    "NI" => ["iso" => "NI", "name" => "Nicaragua", "name_fa" => "نیکاراگوئه"],
    "NL" => ["iso" => "NL", "name" => "Netherlands[note 1]", "name_fa" => "هلند"],
    "NO" => ["iso" => "NO", "name" => "Norway", "name_fa" => "نروژ"],
    "NP" => ["iso" => "NP", "name" => "Nepal", "name_fa" => "نپال"],
    "NR" => ["iso" => "NR", "name" => "Nauru", "name_fa" => "نائورو"],
    "NU" => ["iso" => "NU", "name" => "Niue", "name_fa" => "نیووی"],
    "NZ" => ["iso" => "NZ", "name" => "New Zealand", "name_fa" => "نیوزیلند"],
    "OM" => ["iso" => "OM", "name" => "Oman", "name_fa" => "عمان"],
    "PA" => ["iso" => "PA", "name" => "Panama", "name_fa" => "پاناما"],
    "PE" => ["iso" => "PE", "name" => "Peru", "name_fa" => "پرو"],
    "PF" => ["iso" => "PF", "name" => "French Polynesia", "name_fa" => "پلی‌نزی فرانسه"],
    "PG" => ["iso" => "PG", "name" => "Papua New Guinea", "name_fa" => "پاپوآ گینه نو"],
    "PH" => ["iso" => "PH", "name" => "Philippines", "name_fa" => "فیلیپین"],
    "PK" => ["iso" => "PK", "name" => "Pakistan", "name_fa" => "پاکستان"],
    "PL" => ["iso" => "PL", "name" => "Poland", "name_fa" => "لهستان"],
    "PM" => ["iso" => "PM", "name" => "Saint Pierre and Miquelon", "name_fa" => "سن پیر و میکلن"],
    "PN" => ["iso" => "PN", "name" => "Pitcairn", "name_fa" => "جزایر پیت‌کرن"],
    "PR" => ["iso" => "PR", "name" => "Puerto Rico", "name_fa" => "پورتوریکو"],
    "PS" => ["iso" => "PS", "name" => "Palestine, State of", "name_fa" => "Palestinian Territory, Occupied"],
    "PT" => ["iso" => "PT", "name" => "Portugal", "name_fa" => "پرتغال"],
    "PW" => ["iso" => "PW", "name" => "Palau", "name_fa" => "پالائو"],
    "PY" => ["iso" => "PY", "name" => "Paraguay", "name_fa" => "پاراگوئه"],
    "QA" => ["iso" => "QA", "name" => "Qatar", "name_fa" => "قطر"],
    "RE" => ["iso" => "RE", "name" => "Réunion", "name_fa" => "رئونیون"],
    "RO" => ["iso" => "RO", "name" => "Romania", "name_fa" => "رومانی"],
    "RS" => ["iso" => "RS", "name" => "Serbia", "name_fa" => "صربستان"],
    "RU" => ["iso" => "RU", "name" => "Russian Federation", "name_fa" => "روسیه"],
    "RW" => ["iso" => "RW", "name" => "Rwanda", "name_fa" => "رواندا"],
    "SA" => ["iso" => "SA", "name" => "Saudi Arabia", "name_fa" => "عربستان سعودی"],
    "SB" => ["iso" => "SB", "name" => "Solomon Islands", "name_fa" => "جزایر سلیمان"],
    "SC" => ["iso" => "SC", "name" => "Seychelles", "name_fa" => "سیشل"],
    "SD" => ["iso" => "SD", "name" => "Sudan", "name_fa" => "سودان"],
    "SE" => ["iso" => "SE", "name" => "Sweden", "name_fa" => "سوئد"],
    "SG" => ["iso" => "SG", "name" => "Singapore", "name_fa" => "سنگاپور"],
    "SH" => [
        "iso" => "SH",
        "name" => "Saint Helena, Ascension and Tristan da Cunha",
        "name_fa" => "سنت هلنا، اسنشن و تریستان دا کونا"
    ],
    "SI" => ["iso" => "SI", "name" => "Slovenia", "name_fa" => "اسلوونی"],
    "SJ" => ["iso" => "SJ", "name" => "Svalbard and Jan Mayen", "name_fa" => "سوالبارد و یان ماین"],
    "SK" => ["iso" => "SK", "name" => "Slovakia", "name_fa" => "اسلواکی"],
    "SL" => ["iso" => "SL", "name" => "Sierra Leone", "name_fa" => "سیرالئون"],
    "SM" => ["iso" => "SM", "name" => "San Marino", "name_fa" => "سن مارینو"],
    "SN" => ["iso" => "SN", "name" => "Senegal", "name_fa" => "سنگال"],
    "SO" => ["iso" => "SO", "name" => "Somalia", "name_fa" => "سومالی"],
    "SR" => ["iso" => "SR", "name" => "Suriname", "name_fa" => "سورینام"],
    "SS" => ["iso" => "SS", "name" => "South Sudan", "name_fa" => "سودان جنوبی"],
    "ST" => ["iso" => "ST", "name" => "Sao Tome and Principe", "name_fa" => "سائوتومه و پرینسیپ"],
    "SV" => ["iso" => "SV", "name" => "El Salvador", "name_fa" => "السالوادور"],
    "SX" => ["iso" => "SX", "name" => "Sint Maarten (Dutch part)", "name_fa" => "سینت مارتن"],
    "SY" => ["iso" => "SY", "name" => "Syrian Arab Republic", "name_fa" => "سوریه"],
    "SZ" => ["iso" => "SZ", "name" => "Eswatini", "name_fa" => "سوازیلند"],
    "TC" => ["iso" => "TC", "name" => "Turks and Caicos Islands", "name_fa" => "جزایر تورکس و کایکوس"],
    "TD" => ["iso" => "TD", "name" => "Chad", "name_fa" => "چاد"],
    "TF" => ["iso" => "TF", "name" => "French Southern Territories", "name_fa" => "سرزمین‌های جنوبی و جنوبگانی فرانسه"],
    "TG" => ["iso" => "TG", "name" => "Togo", "name_fa" => "توگو"],
    "TH" => ["iso" => "TH", "name" => "Thailand", "name_fa" => "تایلند"],
    "TJ" => ["iso" => "TJ", "name" => "Tajikistan", "name_fa" => "تاجیکستان"],
    "TK" => ["iso" => "TK", "name" => "Tokelau", "name_fa" => "توکلائو"],
    "TL" => ["iso" => "TL", "name" => "Timor-Leste", "name_fa" => "تیمور شرقی"],
    "TM" => ["iso" => "TM", "name" => "Turkmenistan", "name_fa" => "ترکمنستان"],
    "TN" => ["iso" => "TN", "name" => "Tunisia", "name_fa" => "تونس"],
    "TO" => ["iso" => "TO", "name" => "Tonga", "name_fa" => "تونگا"],
    "TR" => ["iso" => "TR", "name" => "Turkey", "name_fa" => "ترکیه"],
    "TT" => ["iso" => "TT", "name" => "Trinidad and Tobago", "name_fa" => "ترینیداد و توباگو"],
    "TV" => ["iso" => "TV", "name" => "Tuvalu", "name_fa" => "تووالو"],
    "TW" => ["iso" => "TW", "name" => "Taiwan, Province of China ", "name_fa" => "تایوان"],
    "TZ" => ["iso" => "TZ", "name" => "Tanzania,  United Republic of", "name_fa" => "تانزانیا"],
    "UA" => ["iso" => "UA", "name" => "Ukraine", "name_fa" => "اوکراین"],
    "UG" => ["iso" => "UG", "name" => "Uganda", "name_fa" => "اوگاندا"],
    "UM" => ["iso" => "UM", "name" => "United States Minor Outlying Islands", "name_fa" => "ایالات متحده آمریکا"],
    "US" => ["iso" => "US", "name" => "United States of America", "name_fa" => "ایالات متحده آمریکا"],
    "UY" => ["iso" => "UY", "name" => "Uruguay", "name_fa" => "اروگوئه"],
    "UZ" => ["iso" => "UZ", "name" => "Uzbekistan", "name_fa" => "ازبکستان"],
    "VA" => ["iso" => "VA", "name" => "Holy See", "name_fa" => "واتیکان"],
    "VC" => ["iso" => "VC", "name" => "Saint Vincent and the Grenadines", "name_fa" => "سنت وینسنت و گرنادین‌ها"],
    "VE" => ["iso" => "VE", "name" => "Venezuela (Bolivarian Republic of)", "name_fa" => "ونزوئلا"],
    "VG" => ["iso" => "VG", "name" => "Virgin Islands (British)", "name_fa" => "جزایر ویرجین بریتانیا"],
    "VI" => ["iso" => "VI", "name" => "Virgin Islands (U.S.)", "name_fa" => "جزایر ویرجین ایالات متحده"],
    "VN" => ["iso" => "VN", "name" => "Viet Nam", "name_fa" => "ویتنام"],
    "VU" => ["iso" => "VU", "name" => "Vanuatu", "name_fa" => "وانواتو"],
    "WF" => ["iso" => "WF", "name" => "Wallis and Futuna", "name_fa" => "والیس و فوتونا"],
    "WS" => ["iso" => "WS", "name" => "Samoa", "name_fa" => "ساموآ"],
    "YE" => ["iso" => "YE", "name" => "Yemen", "name_fa" => "یمن"],
    "YT" => ["iso" => "YT", "name" => "Mayotte", "name_fa" => "مایوت"],
    "ZA" => ["iso" => "ZA", "name" => "South Africa", "name_fa" => "آفریقای جنوبی"],
    "ZM" => ["iso" => "ZM", "name" => "Zambia", "name_fa" => "زامبیا"],
    "ZW" => ["iso" => "ZW", "name" => "Zimbabwe", "name_fa" => "زیمبابوه"],
];