<?php

namespace rabint\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use rabint\filters\EnvironmentFilter;

class AdminController extends Controller
{

    var $layout = '@themeLayouts/main';
    var $renderFlashOnAjax = true;

    public function behaviors()
    {
        $mustAdd = func_get_args();
        $mustAdd = (isset($mustAdd[0])) ? $mustAdd[0] : [];

        return array_merge([
            'environment' => [
                'class' => EnvironmentFilter::class,
                'actions' => [
                    '*' => 'admin',
                ],
            ],
        ],$mustAdd);
    }

    public function init()
    {
        if (\rabint\helpers\user::isGuest()) {
            Yii::$app->session->setFlash('warning', \Yii::t('rabint', 'لطفا ابتدا وارد حساب کاربری خود شوید'));
            return redirect(['/user/sign-in/login']);
        }

//        $roles = Yii::$app->authManager->getRoles();
//        if (is_array($roles) and count($roles)) {
//            $role = array_shift($roles);
//            return $role->name;
//        }

        if (!\rabint\helpers\user::can(\common\models\User::ROLE_MANAGER)) {
            throw new \yii\web\ForbiddenHttpException(\Yii::t('rabint', 'شما به این صفحه دسترسی ندارید.'));
            //            Yii::$app->session->setFlash('warning', \Yii::t('rabint', 'شما به این صفحه دسترسی ندارید.'));
            //            $url = \Yii::$app->urlManagerApp->createAbsoluteUrl(['/'], true);
            ////            var_dump($url);
            ////            die('--');
            //            return \rabint\helpers\uri::redirect($url);
        }

        EnvironmentFilter::setEnv(EnvironmentFilter::ENV_ADMIN);

        //Yii::$app->params['bsVersion'] = '3.x';
        return parent::init();
    }

    public function render($view, $params = [], $handleAjax = true)
    {
        if ($handleAjax && Yii::$app->request->isAjax) {
            if (!$this->renderFlashOnAjax) {
                return $this->renderAjax($view, $params);
            }
            $allFlashes = Yii::$app->session->getAllFlashes();
            $text = '';
            if ($allFlashes) {
                $text = '
           <section class="sec-flashes fixed">
               <div class="container">
                   <div class="row">
                       <div class="col">';
                foreach ($allFlashes as $type => $body) {
                    $text .= '<div class="alert alert-'.$type.' alert-dismissable">
                                   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>' .
                        print_r($body, TRUE) .
                        '</div>';
                }
                $text .= '</div>
                   </div>
               </div>
           </section>';
            }
            $text = $text .''. $this->renderAjax($view, $params);
            return $text;
        }
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}
