<?php

namespace rabint\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class DefaultController extends Controller
{

    public function init()
    {
        \rabint\helpers\currency::setCurrency(\rabint\helpers\currency::CURRENCY_IR_TOMAN);
        return parent::init();
    }

    public function beforeAction($action)
    {

        //        if (!strpos(config("HOST_BASE_URL"), $_SERVER['HTTP_HOST'])) {
        //            $redirect = config("HOST_BASE_URL") . $_SERVER['REQUEST_URI'];
        //            header('HTTP/1.1 301 Moved Permanently');
        //            header('Location: ' . $redirect);
        //            exit();
        //        }

        //        if (Yii::$app->keyStorage->get('app.maintenance') === 'enabled') {
        //            if ($this->className() != 'app\controllers\MainController' OR $action->id != 'maintenance')
        //                return $this->redirect(['/site/maintenance']);
        //        }

        return parent::beforeAction($action);
    }

    public function render($view, $params = [], $handleAjax = true)
    {
        if ($handleAjax && Yii::$app->request->isAjax) {
            $return = $this->renderAjax($view, $params);
            Yii::$app->response->getHeaders()->add('x-response-title', json_encode($this->view->title));
            return $return;
        }

        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}
