<?php

namespace rabint\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PanelController extends Controller
{

    public function behaviors()
    {

        $mustAdd = func_get_args();
        $mustAdd = (isset($mustAdd[0])) ? $mustAdd[0] : [];

        return array_merge($mustAdd, [
            'environment' => [
                'class' => \rabint\filters\EnvironmentFilter::className(),
                'actions' => [
                    '*' => 'panel',
                ],
            ],
        ]);
    }

    public function render($view, $params = [], $handleAjax = true)
    {
        if ($handleAjax && Yii::$app->request->isAjax) {
            return $this->renderAjax($view, $params);
        }

        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}
