<?php


namespace rabint\models;


use rabint\models\query\LangActiveQuery;

class LangActiveRecord extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function langRules()
    {
        return [
            [['lang'], 'string', 'max' => 5],
            [['otherlang'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function langAttributeLabels()
    {
        return [
            'lang' => \Yii::t('rabint', 'زبان'),
            'otherlang' => \Yii::t('rabint', 'دیگر زبان ها'),
        ];
    }


    /**
     * Generate DetailView for lang
     *
     * @return array
     */

    public function beforeSave($insert)
    {
        if ($this->hasAttribute('lang') && empty($this->lang)) {
            $this->lang = \Yii::$app->language;
        }
        if ($this->hasAttribute('otherlang') && empty($this->otherlang)) {
            if (\Yii::$app->request->get('otherlang') != null) {
                $this->otherlang = \Yii::$app->request->get('otherlang');
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getLangDetailView()
    {
        return ['attribute' => 'lang'];
    }


    /**
     * Generate DetailView for otherlang
     *
     * @return string
     */
    public function getOtherlangDetailView()
    {
        return [
            'attribute' => 'otherlang',
            'format' => 'html',
//            'value' => $this->otherlang ? Html::a($this->otherlang->username, urldecode(Url::toRoute(['/user/admin/update', 'id' => $this->otherlang]))) : Yii::t('traits', 'Nobody'),
            'value' => $this->otherlang,
            'valueColOptions' => [
                'style' => 'width:30%'
            ]
        ];
    }


    /**
     * Generate GridView for otherlang
     *
     * @return string
     */
    public function getLangGridView()
    {
        return $this->lang;
    }

    /**
     * Generate GridView for otherlang
     *
     * @return string
     * @throws InvalidParamException
     */
    public function getOtherlangGridView()
    {
//        $url = urldecode(Url::toRoute(['/user/profile/show', 'id' => $this->created_by]));
//        $otherlang = isset($this->otherlang->username) ? $this->otherlang->username : '';
//        if ($this->created_by) {
//            return Html::a($otherlang, $url);
//        }
//        return Yii::t('rabint', 'Nobody');
        return $this->otherlang;
    }


    public static function find()
    {
        return new LangActiveQuery(get_called_class());
    }

}