<?php
/**
 * Created by PhpStorm.
 * User: mojtaba
 * Date: 4/17/19
 * Time: 9:54 AM
 */

namespace rabint\models;


class MysqlToMongoActiveRecord extends \yii\mongodb\ActiveRecord
{

//    public function getId()
//    {
//        $this->_id;
//    }

    public static function tableName()
    {
        return '{{%' . Inflector::camel2id(StringHelper::basename(get_called_class()), '_') . '}}';
    }

    public function attributeLabels()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public static function collectionName()
    {
//        if (strpos($name, '{{') !== false) {
//            $name = preg_replace('/\\{\\{(.*?)\\}\\}/', '\1', $name);
//
//            return str_replace('%', $this->db->tablePrefix, $name);
//        }
//
//        return $name;
//        return ['open', 'opn_company'];
        return static::tableName();
    }

    /**
     * {@inheritdoc}
     */
    public function attributes()
    {
        return array_merge(['_id'], array_keys($this->attributeLabels()));
    }

    public function beforeSave($insert)
    {
        $this->id = self::find()->max("id")+1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}